In [1]:
import pandas as pd
#First look at the data
df = pd.read_csv("fraudTest.csv", index_col="trans_num")

df.drop_duplicates(inplace=True)
df.dropna(inplace=True)

df.rename(columns= {df.columns[0]: "ID"} , inplace=True)

df

,ID,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,zip,lat,long,city_pop,job,dob,unix_time,merch_lat,merch_long,is_fraud
trans_num,,,,,,,,,,,,,,,,,,,,,
2da90c7d74bd46a0caf3777415b3ebd3,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,29209,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,1371816865,33.986391,-81.200714,0
324cc204407e99f51b0d6ca0055005e7,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,84002,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,1371816873,39.450498,-109.960431,0
c81755dbbbea9d5c77f094348a7579be,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,11710,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,1371816893,40.495810,-74.196111,0
2159175b9efe66dc301f149d3d5abf8c,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,32780,28.5697,-80.8191,54767,Set designer,1987-07-25,1371816915,28.812398,-80.883061,0
57ff021bd3f328f8738bb535c302a31b,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,49632,44.2529,-85.0170,1126,Furniture designer,1955-07-06,1371816917,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9b1f753c79894c9f4b71f04581835ada,555714,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,...,63453,40.4931,-91.8912,519,Town planner,1966-02-13,1388534347,39.946837,-91.333331,0
2090647dac2c89a1d86c514c427f5b91,555715,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,...,77566,29.0393,-95.4401,28739,Futures trader,1999-12-27,1388534349,29.661049,-96.186633,0
6c5b7c8add471975aa0fec023b2e8408,555716,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,...,99323,46.1966,-118.9017,3684,Musician,1981-11-29,1388534355,46.658340,-119.715054,0
14392d723bb7737606b2700ac791b7aa,555717,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,...,83643,44.6255,-116.4493,129,Cartographer,1965-12-15,1388534364,44.470525,-117.080888,0
1765bb45b3aa3224b4cdcb6e7a96cee3,555718,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,...,73034,35.6665,-97.4798,116001,Media buyer,1993-05-10,1388534374,36.210097,-97.036372,0

In [2]:
print(df.info())

print(df.describe())

print(df.shape)

<class 'pandas.DataFrame'>
Index: 555719 entries, 2da90c7d74bd46a0caf3777415b3ebd3 to 1765bb45b3aa3224b4cdcb6e7a96cee3
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  str
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  str
 4   category               555719 non-null  str
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  str
 7   last                   555719 non-null  str
 8   gender                 555719 non-null  str
 9   street                 555719 non-null  str
 10  city                   555719 non-null  str
 11  state                  555719 non-null  str
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  str
 17  dob                    555719 non-null  str
 18  unix_time              555719 non-null  int64
 19  merch_lat              555719 non-null  float64
 20  merch_long             555719 non-null  float64
 21  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), str(11)
memory usage: 113.6+ MB
None
                  ID        cc_num            amt            zip  \
count  555719.000000  5.557190e+05  555719.000000  555719.000000
mean   277859.000000  4.178387e+17      69.392810   48842.628015
std    160422.401459  1.309837e+18     156.745941   26855.283328
min         0.000000  6.041621e+10       1.000000    1257.000000
25%    138929.500000  1.800429e+14       9.630000   26292.000000
50%    277859.000000  3.521417e+15      47.290000   48174.000000
75%    416788.500000  4.635331e+15      83.010000   72011.000000
max    555718.000000  4.992346e+18   22768.110000   99921.000000

                 lat           long      city_pop     unix_time  \
count  555719.000000  555719.000000  5.557190e+05  5.557190e+05
mean       38.543253     -90.231325  8.822189e+04  1.380679e+09
std         5.061336      13.721780  3.003909e+05  5.201104e+06
min        20.027100    -165.672300  2.300000e+01  1.371817e+09
25%        34.668900     -96.798000  7.410000e+02  1.376029e+09
50%        39.371600     -87.476900  2.408000e+03  1.380762e+09
75%        41.894800     -80.175200  1.968500e+04  1.385867e+09
max        65.689900     -67.950300  2.906700e+06  1.388534e+09

           merch_lat     merch_long       is_fraud
count  555719.000000  555719.000000  555719.000000
mean       38.542798     -90.231380       0.003860
std         5.095829      13.733071       0.062008
min        19.027422    -166.671575       0.000000
25%        34.755302     -96.905129       0.000000
50%        39.376593     -87.445204       0.000000
75%        41.954163     -80.264637       0.000000
max        66.679297     -66.952026       1.000000
(555719, 22)

In [3]:
df['is_fraud'] = df['is_fraud'].astype(int)
print(df['is_fraud'].value_counts())

is_fraud
0    553574
1      2145
Name: count, dtype: int64

In [4]:
df['Merchant_Frequency'] = df['merchant'].map(df['merchant'].value_counts())

df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])

df['Hour'] = df['trans_date_trans_time'].dt.hour
df['Day_of_week'] = df['trans_date_trans_time'].dt.dayofweek
df['Is_weekend'] = df['Day_of_week'].isin([5,6]).astype(int)

df = df.drop('trans_date_trans_time', axis=1)

df['Transactions_per_user'] = df.groupby('cc_num')['amt'].transform('count')
df['Avg_amount_per_user'] = df.groupby('cc_num')['amt'].transform('mean')

df.head(3)

,ID,cc_num,merchant,category,amt,first,last,gender,street,city,...,unix_time,merch_lat,merch_long,is_fraud,Merchant_Frequency,Hour,Day_of_week,Is_weekend,Transactions_per_user,Avg_amount_per_user
trans_num,,,,,,,,,,,,,,,,,,,,,
2da90c7d74bd46a0caf3777415b3ebd3,0,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,Columbia,...,1371816865,33.986391,-81.200714,0,736,12,6,1,640,61.893062
324cc204407e99f51b0d6ca0055005e7,1,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,Altonah,...,1371816873,39.450498,-109.960431,0,785,12,6,1,837,53.596523
c81755dbbbea9d5c77f094348a7579be,2,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,Bellmore,...,1371816893,40.495810,-74.196111,0,755,12,6,1,1073,83.053812

In [5]:
X = df.select_dtypes(include=['number'])
X = X.drop(columns = ["ID", "is_fraud"])

y = df["is_fraud"]

print(X.shape)

(555719, 15)

In [6]:
# One Hot Encoding
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import hstack
import numpy as np

categorical_values = df.select_dtypes(include=['object', 'string'] )
encoder = OneHotEncoder(sparse_output = True, dtype= np.uint8, handle_unknown='ignore')
encoder.fit(categorical_values)
categorical_values_encoded = encoder.transform(categorical_values)

#Now, concatenating the encoded categorical values with the numerical features
categorical_values_encoded_df = pd.DataFrame.sparse.from_spmatrix(categorical_values_encoded, index = categorical_values.index,
                                                                  columns=encoder.get_feature_names_out(categorical_values.columns))
print(X.shape)

(555719, 15)

In [7]:
from sklearn.model_selection import train_test_split

# Splitting the testing and training data 80% - 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=10)

In [8]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=10)
X_train_scaled, y_train_scaled = smote.fit_resample(X_train, y_train)

In [9]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=50, n_jobs=-1,
                                    max_depth=None, min_samples_split=2, 
                                    criterion= 'gini', min_samples_leaf=1, 
                                    class_weight = 'balanced', random_state=10)

classifier.fit(X_train_scaled, y_train_scaled)

RandomForestClassifier(class_weight='balanced', n_estimators=50, n_jobs=-1,
                       random_state=10)

In [ ]:
# I tried running the RandomizedSearchCV, but it took 99 mins to complete. So I just took the best hyperparams it gave me.
'''param_grid = {
    'n_estimators': [10, 20, 50, 100],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'criterion': ['gini', 'entropy'],
}

rand_search = RandomizedSearchCV(estimator=classifier, param_distributions=param_grid, cv=5, n_jobs=-1, scoring = 'f1', n_iter=30)

rand_search.fit(X_train_scaled, y_train_scaled)

print(f"Best parameters: {rand_search.best_params_}")
print(f"Best score: {rand_search.best_score_}")
'''

'''Best parameters: {'n_estimators': 50, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_depth': None, 'criterion': 'gini'}
Best score: 0.9990197300982956'''

In [11]:
y_predicted = classifier.predict(X_test)

y_probability = classifier.predict_proba(X_test)[:,1]

print(y_predicted, y_probability)
print(len(y_predicted), "                        ",len(y_probability))

[0 0 0 ... 0 0 0] [0. 0. 0. ... 0. 0. 0.]
111144                          111144

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, precision_recall_curve, average_precision_score

print("Classification report: ")
print()
print(classification_report(y_test, y_predicted))
print()

print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_predicted))
print()

print()
print(f"ROC_AUC Score: {roc_auc_score(y_test, y_probability)}")
print()

print()
print("Precision-Recall Curve:")
precision, recall, thresholds = precision_recall_curve(y_test, y_probability)
for p, r, t in zip(precision, recall, thresholds):
    print(f"Threshold: {t:.2f}, Precision: {p:.2f}, Recall: {r:.2f}")

print()
print(f"Average Precision Score: {average_precision_score(y_test, y_probability)}")

Classification report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    110715
           1       0.65      0.77      0.70       429

    accuracy                           1.00    111144
   macro avg       0.82      0.88      0.85    111144
weighted avg       1.00      1.00      1.00    111144



Confusion Matrix:
[[110535    180]
 [    98    331]]


ROC_AUC Score: 0.9886071010986334


Precision-Recall Curve:
Threshold: 0.00, Precision: 0.00, Recall: 1.00
Threshold: 0.02, Precision: 0.03, Recall: 0.99
Threshold: 0.04, Precision: 0.05, Recall: 0.97
Threshold: 0.06, Precision: 0.08, Recall: 0.96
Threshold: 0.08, Precision: 0.10, Recall: 0.95
Threshold: 0.10, Precision: 0.12, Recall: 0.94
Threshold: 0.12, Precision: 0.15, Recall: 0.94
Threshold: 0.14, Precision: 0.17, Recall: 0.92
Threshold: 0.16, Precision: 0.19, Recall: 0.90
Threshold: 0.18, Precision: 0.21, Recall: 0.90
Threshold: 0.20, Precision: 0.24, Recall: 0.89
Threshold: 0.22, Precision: 0.27, Recall: 0.88
Threshold: 0.24, Precision: 0.29, Recall: 0.88
Threshold: 0.26, Precision: 0.32, Recall: 0.87
Threshold: 0.28, Precision: 0.34, Recall: 0.86
Threshold: 0.30, Precision: 0.37, Recall: 0.86
Threshold: 0.32, Precision: 0.40, Recall: 0.86
Threshold: 0.34, Precision: 0.43, Recall: 0.85
Threshold: 0.36, Precision: 0.46, Recall: 0.84
Threshold: 0.38, Precision: 0.49, Recall: 0.83
Threshold: 0.40, Precision: 0.52, Recall: 0.83
Threshold: 0.42, Precision: 0.54, Recall: 0.81
Threshold: 0.44, Precision: 0.56, Recall: 0.80
Threshold: 0.46, Precision: 0.58, Recall: 0.80
Threshold: 0.48, Precision: 0.60, Recall: 0.78
Threshold: 0.50, Precision: 0.63, Recall: 0.78
Threshold: 0.52, Precision: 0.65, Recall: 0.77
Threshold: 0.54, Precision: 0.68, Recall: 0.77
Threshold: 0.56, Precision: 0.70, Recall: 0.76
Threshold: 0.58, Precision: 0.72, Recall: 0.76
Threshold: 0.60, Precision: 0.74, Recall: 0.75
Threshold: 0.62, Precision: 0.76, Recall: 0.73
Threshold: 0.64, Precision: 0.79, Recall: 0.72
Threshold: 0.66, Precision: 0.80, Recall: 0.71
Threshold: 0.68, Precision: 0.83, Recall: 0.69
Threshold: 0.70, Precision: 0.85, Recall: 0.68
Threshold: 0.72, Precision: 0.87, Recall: 0.67
Threshold: 0.74, Precision: 0.88, Recall: 0.66
Threshold: 0.76, Precision: 0.89, Recall: 0.66
Threshold: 0.78, Precision: 0.90, Recall: 0.64
Threshold: 0.80, Precision: 0.91, Recall: 0.62
Threshold: 0.82, Precision: 0.92, Recall: 0.61
Threshold: 0.84, Precision: 0.93, Recall: 0.60
Threshold: 0.86, Precision: 0.93, Recall: 0.57
Threshold: 0.88, Precision: 0.95, Recall: 0.55
Threshold: 0.90, Precision: 0.97, Recall: 0.52
Threshold: 0.92, Precision: 0.98, Recall: 0.48
Threshold: 0.94, Precision: 0.98, Recall: 0.43
Threshold: 0.96, Precision: 0.99, Recall: 0.38
Threshold: 0.98, Precision: 0.98, Recall: 0.31
Threshold: 1.00, Precision: 0.98, Recall: 0.19

Average Precision Score: 0.7908774416726119

In [13]:
# Threshold tuning

from sklearn.metrics import precision_recall_curve
threshold = 0.3
y_predicted_custom = (y_probability > threshold).astype(int)

print(y_predicted_custom)

[0 0 0 ... 0 0 0]

In [ ]:
''' New features to add: 
1. Find a way to use the merchant name and category to create new features. Maybe use one hot encoding or something like that.
2. Use the day,hour and time of the transaction to create new features. Maybe use the hour of the day or the day of the week. 
Also track the number of operatins performed by each person. (Feature engineering.)
3. More hyperparameter tuning. Maybe use GridSearchCV or RandomizedSearchCV to find the best hyperparameters for the model.
4. Precision-recall curve and AUC-PR score. This is especially important for imbalanced datasets like this one.
5. Extra cross-validation using StratifiedKFOld and cross_val_score.
6. Extract insights from the model.
7. Threshold tuning. Find the best threshold for the model to maximize the F1 score or the precision-recall curve.
8. Most importantly, use matplotlib to visualize the data better.
9. Use feature importance to find the most important features for the model.
10. Test it with XGBoost and see.

11. Use SHAP values to explain the model predictions. (Not important right now so skippable.)
'''